### ISSUE TITLE
pen 典型的“不说人话”写作风格

### ISSUE THREAD

**Issue by andyzhaozhao** [archguard/book#2]
大佬，文档这么写，感觉像是ppt，不像是正经文档。可否别这么装。

**Comment by andyzhaozhao** [comment]
毕竟，文档写出来还弄个官网连接，就是给人看的了。不是大佬自己的笔记自己看的吧。

**Comment by phodal** [comment]
About 里写得很清楚了： 

> 《架构治理模式》介绍了一系列调整现有人员、流程和技术的实践与模式，使架构符合架构师预期的设想，以最好地帮助架构师交付业务成果。 

和官方文档没有关系，就是做架构治理可以参考的内容。
